.github/dependabot.yml
eaf-pdf-viewer.el

And also added some documentation for all the defcustoms.
Here's the before-and-after
https://pasteboard.co/KgnYk1q.png

Prettier outline buffer, deriving from outline mode

---

eaf-pdf-viewer.el

Hi,
I create this PR to handle the case that EAF pdf-viewer fails to synchronize backward and forward LaTeX and PDF files whose paths and names containing whitespace characters.
What I did is to wrap those paths with a pair of double-quotes `"..."`
Can you advise if the patch is suitable?

wrap Pdf and Tex file paths containing whitespace with double quote

---

README.md
buffer.py
eaf-pdf-viewer.el

tidy Inverted mode

---

buffer.py

Hi,
In the previous code, when a text annot is being edited, if I left-click the mouse on the PDF file, then another editing window will be created to create a new annot.
I fix this issue in this PR by adding flags to check if there is any text annot being edited.

check if a text annot is being handled to prevent creating another text annot

---

buffer.py
eaf-pdf-viewer.el

Hi,
This PR will fix the issue https://github.com/emacs-eaf/eaf-pdf-viewer/issues/34

Update user information to text annotations 

---

buffer.py

Hi,
I fix this issue https://github.com/emacs-eaf/eaf-pdf-viewer/issues/37 by catching exceptions when loading PDF files

catch exception when loading broken PDF files to prevent EAF pdf-viewer from terminate unexpectedly

---

buffer.py

#48  Fix QFileSystemWatcher is invalid when emit once

Fix document reload but not updated viewer status

---

eaf-pdf-viewer.el

for example when open related pdf of test.tex, the path is test.pdf"

fix pdf path error when call TeX-view

---

buffer.py

PyMupdf API changed. :crying_cat_face:

Fix select text not working

---

buffer.py

Highlight select area use pixmap compose

---

buffer.py

hover annot 的一些基本操作测试了下，没有什么问题。

Fix hover annot

---

eaf_pdf_page.py

Or it will crash when drawing annotations

Fix API Change in PyQt6

---

eaf_pdf_widget.py

Many times I just want to add a text for highlight or underline annotation, So I make this patch

Make any annotation can add text

---

eaf_pdf_page.py
eaf_pdf_widget.py

Convert camel case to snake case

---

eaf_pdf_buffer.py
eaf_pdf_widget.py

https://github.com/emacs-eaf/eaf-pdf-viewer/issues/91

fix issue  #91 for small size pdf.

---

eaf_pdf_document.py

fix reload when generating latex pdf file

---

eaf_pdf_widget.py

Hi,
This PR supports showing the mouse cursor in a palm shape when hovering over URLs.
It also supports open links in external browsers by clicking RightMouse or Ctrl + LeftMouse.

change cursor when hovering over URLs and open by external browser

---

eaf_pdf_buffer.py
eaf_pdf_page.py
eaf_pdf_widget.py

Hi,
This PR implements the isearch-like feature. It supports:
- Highlight the current search text
- Jump the search location when search forward/backward
- Search from the current page
Here is a screenshot: the light blue color is the current search:
Hope that it'll be helpful.

support interactive search like isearch

---

eaf_pdf_widget.py

This PR allows jumping between pages easily using forward, backward, middle button of mouse.

remember position and jump backward/forward when clicking on href links

---

eaf_pdf_widget.py

This PR checks if the jump offset doesn't exceed the viewable area of the last page.

adjust jump offset to never jump beyond the last page

---

eaf_pdf_buffer.py
eaf_pdf_widget.py

This PR enables showing arrow indicator when jumping to page. Similar to synctex indicator too.

show arrow indicator when jumping to page

---

eaf-pdf-viewer.el

Pressing the key "O" (eaf-pdf-outline-edit) creates a new outline buffer every time, even if one already exists for the same PDF. This results in multiple outline buffers being created unnecessarily, 
This commit checks if an outline buffer already exists, if it does, reuse the existing buffer instead of creating a new one.

reusing existing outline buffer if already open

---

README.md
eaf-pdf-viewer.el
eaf_pdf_buffer.py
eaf_pdf_widget.py

support search toc in minibuffer using narow-search, also and a AppBuffer._is_caching variable to prevent concurrent caching

add TOC option for narrow-search

---

eaf_pdf_buffer.py
eaf_pdf_widget.py

I removed the codes that constrained link jumping for EPUB and tweaked the offset calculation. I found that it works as expected.

unlock link jump for EPUB

---

README.md
eaf-pdf-viewer.el
eaf_pdf_buffer.py
eaf_pdf_document.py
eaf_pdf_page.py
eaf_pdf_widget.py

these commits mainly aim to implement accurate text selecton and click to copy utils:
- The first commit addresses the bugs in current coordinate conversion mechanism by using a more precise prefix-sum array based y-coordinate calculation algorithm.
- The second commit introduces character hover detection just like in common pdf viewers and ensures accurate text synchronization during double-click selection.
- The third commit refactors the codebase to align with the updated y-coordinate calculation.
- The final commit adds the click-to-copy feature, allowing users to copy selected text with a simple click after selection.
the selection remain  work in trim mode

Support accurate text selection and click to copy

---

eaf_pdf_widget.py

last serveral commit has introduced a bug that allows negative scroll offset, this commit fix it

ensure vertical offset is within bounds in update_vertical_offset method
