emacs-eaf/eaf-pdf-viewer

buffer.py, eaf-pdf-viewer.el
for eaf.el use marker instead of mark.
=> eaf-pdf-mark-fontsize -> eaf-pdf-marker-fontsize

buffer.py, eaf-pdf-viewer.el
Hi,
I created this PR to include an option `eaf-pdf-notify-file-changed` which can control whether EAF pdf-viewer will notify users when pdf files are changed.
This option is useful when EAF pdf-viewer is used as the backend PDF viewer of AuxTex: I can set `eaf-pdf-notify-file-changed` to `nil` so that EAF will keep silent and compilation messages from AuxTex will not be overwritten by EAF.
Can you advise if it can be merged back to your repo?
Thanks!
=> option to enable/disable notification of file changed

buffer.py
Hi,
I created this PR to fix the bug https://github.com/emacs-eaf/eaf-pdf-viewer/issues/13.
Now EAF pdf-viewer can make Emacs stay in the LaTeX buffer
=> make Emacs stay in LaTeX buffer when doing synctex backward

buffer.py, eaf-pdf-viewer.el
Hi,
I created this PR to allow PDF files can be manually reloaded by using the key `r`.
This feature is useful when sometimes the auto-reloading feature doesn't work properly. It happens quite often with me when I prepare slides using LaTeX beamer: sometimes when exporting LaTeX to PDF file, new pages are added but EAF pdf-viewer didn't render the new file correctly.
So, in this PR, I also need to update the page_width, height, and total page number to make sure the new file will be reloaded correctly.
Can you advise if this is reasonable and can be merged?
Thank you!
=> support manually reloading PDF document

buffer.py, eaf-pdf-viewer.el
Hi,
In this PR, I improved EAF pdf-viewer in points:
- Compute the current page more precise by the formula `math.floor((self.start_page_index + self.last_page_index + 1) / 2)`. Previously, the current page information ignore the fact about the last_page_index, hence it will be imprecise when the document is zoomed out to show many pages
- Add option to control showing page number on page `eaf-pdf-show-progress-on-page`. This is useful since currently the mode-line can also show the page number, then I can set `eaf-pdf-show-progress-on-page` to `nil` to hide the page infor on the PDF file.
Can you advise if these features can be merged?
Thank you!
=> compute the current page number more precise, and add option to control showing page number directly on PDF page

buffer.py, eaf-pdf-viewer.el
Hi,
I just implemented a simple version of the feature mentioned in this issue https://github.com/emacs-eaf/eaf-pdf-viewer/issues/6.
Now, EAF pdf-viewer can show the indicator when synchronizing from LaTeX to PDF file. 
Here is an illustration screenshot:
Although the current indicator `===>` is quite basic since I'm not proficient in Python and PyQT, at least it can show quite precisely the text location on the PDF file.
Could you review the code if it is OK, and merge it when possible?
Thank you!
=> show an indicator of synchronized text from LaTeX to PDF

buffer.py
Fix bug that mentioned by @MatthewZMD in https://github.com/emacs-eaf/eaf-pdf-viewer/pull/21#issuecomment-921899068
Now EAF pdf-viewer can restore again the last opened location of PDF files.
=> fix bug that affects session restore information

buffer.py, eaf-pdf-viewer.el
Hi,
I created this PR to support inline text annotation, as mentioned in this issue: https://github.com/emacs-eaf/eaf-pdf-viewer/issues/23
In the code, I rename the current `text_annot` naming as `popup_text_annot` naming, and add a new naming `inline_text_annot` for the inline text annotation.
Here is the screenshot of how it looks like (it supports multiple-line inline text annot too!)
I also reassign keybindings a bit to make it more consistent:
- `M-t`: add popup text annot
- `M-T`: add inline text annot
- `M-e`: edit text annot (both)
Can you consider merging it back?
Thank you!
=> support inline text annot

buffer.py
Hi,
Currently, the sync-tex backward feature is only enabled when the PDF is previously opened by a sync-tex forward command.
In this PR, I remove that condition check to allow it can work even when the PDF file is opened normally (like using `C-x C-f`)
=> always attempt to sync-tex backward

buffer.py, eaf-pdf-viewer.el
Hi,
In this PR, I implemented a feature that allows users to move inline and popup text annotation.
- Hover the mouse over a text annot, then a message `[M-d]Delete annot [M-e]Edit text annot [M-r]Move text annot` will appear.
- Press `M-r` (here `r` stands for `rearrange`) -- I didn't use `M-m` since I'm using Spacemacs and `M-m` is a global leading key of Spacemacs.
- Then a message `Move text annot: left-click mouse to choose a target position.` will appear
- Then `left-click` the mouse to the desired location and the text annot will be moved there.
Can you take a look at the code and merge if it is OK?
Thank you!
=> support moving inline and popup text annot

buffer.py
Hi,
This is an optimization to avoid repeatedly printing messages when moving the mouse cursor and hovering over text annotations.
Now, the message is only printed when the mouse cursor first hovers the annotations
=> only print message when hovering mouse in and out of text annot

buffer.py
Hi,
I added a check `is_buffer_focused` to print the annotation editing messages only when a PDF buffer is focused.
Currently, I check this condition by comparing `buffer_url` maintained by the Python app and the `path_url` get from Emacs buffer.
(I tried `self.isActiveWindow` and `self.isFocus` before but the information they return isn't correct).
Can you take a look and merge if it is OK?
Thanks!
=> print annotation editing messages only when PDF buffer is focused

buffer.py, eaf-pdf-viewer.el
Hi,
In this PR, I improve the text highlighting and underlining annotation features to make the stroke colors to be customizable 
This fixed the issue https://github.com/emacs-eaf/eaf-pdf-viewer/issues/32, and help users to be less confused between highlighted text and selected text.
=> make stroke color of text highlight and underline annot customizable

buffer.py
Hi,
This fixes the issue https://github.com/emacs-eaf/eaf-pdf-viewer/issues/33 where EAF pdf-viewer prints ""[M-d]Delete annot" when the mouse cursor hovers selected text.
I fixed it by simply checking that if the annot doesn't have a title, then it's a text selection and will not be highlighted
=> only print message when the mouse cursor hovers annotations, but not selected texts

buffer.py, eaf-pdf-viewer.el
Hi,
In this PR, I make the zoom step to be customizable.
The reason is that the current default zoom step 0.2 sometimes is too big for
some documents.
Using this PR, the user can flexibly set it to a smaller step like 0.1
Could you please consider merging it back?
Thank you!
=> cuztomizable zoom step

eaf_pdf_page.py, eaf_pdf_utils.py, eaf_pdf_widget.py
This is an attempt to fix #68 while maintaining backward compatibility.
- If version >= 1.18.2, use API without `hit_max` keyword arg.
- Replace deprecated `searchFor` with `search_for` in new versions to remove deprecation warning in `*eaf*` buffer.
Feel free to make changes where you see fit.
Minimally tested on my machine with `qt5-legacy` branch. Should apply to `master` branch as well. (Since PyQt6 does not work for my `eaf-browser`, I don't have the environment to test on `master`. NOTE: exactly why my PR is requesting to merge to qt5-legacy branch)
=> Fix API removed keyword 'hit_max' issue. Closes #68.

eaf-pdf-viewer.el, eaf_pdf_buffer.py, eaf_pdf_utils.py
after 1.19.0 version  getToc() rename to get_toc(),  and I add  eaf-pdf-delete-invalid-file-record-from-history function to delete invalid history record
=> fix pymupdf new api after 1.19.0 

README.md, eaf-pdf-viewer.el, eaf_pdf_buffer.py, eaf_pdf_widget.py
In eaf-pdf-viewer hit upper case 'O' to activate eaf-pdf-outline-edit-mode.
The existed table of contents will be got from current PDF file and inserted to eaf-pdf-outline-edit-buffer.
So you can edit the TOC buffer and save it back to TOC of PDF.
In eaf-pdf-outline-edit-mode, 
- Use 'C-c C-c' to confirm editing and save the modification to PDF file.
- Use 'C-c C-k' to quit the mode.
- Hit 'C-return' to jump.
The eaf-pdf-outline-edit-mode is derived from Org-mode.
```
* 主要管理人员的设置 6
** 主要管理人员的一般设置要求 6
```
- Use the number of Org mode style headline which starts with star '*' to control TOC hierarchy(level).
- One star '*' means the most top level of TOC, two star '**' means the second top level of TOC, and so on.
- A space is needed between the star '*' and the title '主要管理人员的设置' of TOC.
- …
=> Support edit PDF table of contents

eaf-pdf-viewer.el, eaf_pdf_widget.py
Hi, 
The current function `zoom-fit-text-width` does not keep any space on the right margin of the pdf page, like the below screenshot.
So, I updated the Zoom ratio of `zoom-fit-text-width` to 0.95 and create a new function `zoom-close-to-text-width` with the zoom ratio 0.8, like the below screenshots.
Can you consider merging this PR?
Thanks!
- The new `zoom-fit-text-width`:
- The function `zoom-close-to-text-width`
=> improve zoom fit to text width

eaf-pdf-viewer.el
Hi,
Currently the variable `synctex-view-command` is not defined in `eaf-pdf--get-tex-and-line`, so there will be this error message if the synctex failed.
```
ERROR:epc:ReturnError([Symbol('void-variable'), Symbol('synctex-view-command')])
```
I just fix this by printing a more informative error message.
Can you review and merge it?
Thanks
=> improve error message when sync-tex backward fails

eaf_pdf_page.py
Hi,
I created this PR to transform background of PDF to transparent if it was previously colored (PDF created by MS Word/PowerPoint is colored by white color).
Here are screenshots in inverted mode of PDF files where some diagrams are created by Power Point.
- Before PR: when PDF is colored by white color, in the inverted mode, the background become black:
- After my PR, the background is transparent:
Can you review and merge if it's useful?
Thanks!
=> make background transparent when PDF is created from MS Word/Powerpoint

eaf_pdf_widget.py
Not sure why the current calculation is incorrect. I adjusted the destination page by 1.
=> rectify the destination page when jumping to

eaf_pdf_widget.py
My previous PR worked for `jump_to_link` but affected the `synctex` feature.
So, I reverted back that commit and adjust the page index in `jump_to_link` instead.
=> revert page index when jump to page and fix index when jump to link

eaf_pdf_widget.py
I improve the link hover feature and fix a segmentation fault issue.
Please consider merging it.
Thanks!
=> use get_links() API to avoid segmentation fault

eaf_pdf_widget.py
This performs some checking to ensure that the accessed page index is valid.
It happened to me in some cases that the page index is larger than the page count, and exceptions were thrown.
=> check if the accessed page index is valid

eaf_pdf_widget.py
Somehow the recent restructuring of eaf-pdf-viewer makes the synctex indicator to be always drawn on page 1, which is wrong!
I fixed that issue in this PR to draw it correctly.
=> draw synctex indicator in the correct page

eaf_pdf_widget.py
I forgot to add these two fields in the previous PR for the jump link feature.
Fixed in this PR.
=> add missing fields for the jump link indicator feature

eaf_pdf_buffer.py
The searched terms later can be queried quickly by `M-p`, `M-n` from Emacs minibuffer
=> add searched term to emacs history

eaf_pdf_widget.py
Somehow the pdf library in my other machine throws an error when the coordinators are of float type.
So, I convert all of them to int type to ensure no error will be thrown.
=> convert coordinators to int type

eaf_pdf_buffer.py, eaf_pdf_widget.py
Hi,
I improved the indicator drawing to indicate a more precise location for both clicking on a hyperref link and synctex (previously, only the synctex indicator is drawn precisely).
Can you consider merging this PR?
Thanks!
=> draw more precise indicator when jumping by hyperref or synctex

README.md
When I am reading a PDF, I need a way to translate the word currently pointed by the cursor. After reading the source code, I discovered that this feature has been implemented.
So I have modified the README to notify others who need this feature.
=> Doc: Add documentation on the ability to translate the current word.

eaf_pdf_document.py, eaf_pdf_widget.py
Hi,
Currently, when a PDF that is opened in EAF PDF Viewer is deleted or renamed, then EAF-PDF-Viewer will constantly display the message `Failed to reload PDF file!`
I fixed this issue by only restarting the timer to reload the PDF file if that file exists.
Can you consider merging this PR?
Thanks!
=> only restart the timer to reload a file if it exits

eaf_pdf_page.py
Hi,
Currently, the PDF background is always made transparent even when the PDF file is viewed in the normal mode. This might affect the display of PDF files that have color backgrounds.
So, I create this PR to process the background only in the invert mode.
Please consider reviewing and merging it.
Thanks!
=> only refine background in the invert mode

eaf-pdf-viewer.el, eaf_pdf_buffer.py, eaf_pdf_widget.py
Change 1: Removed "nil" and opened pdf files from eaf-open-pdf-from-history.
Change 2: Added eaf-pdf-extract-page-text to show text of current page in a new buffer.
Change 3: Fixed reload issue. It is mentioned in https://github.com/emacs-eaf/eaf-pdf-viewer/issues/98, but still exists in current version. After some digging, i think it's related to multi-thread. When i add some annotations on the pdf file, new thread is launched. Close it and reopen it, the annotation thread still exists but the widget related is destroyed. That's why the eaf_pdf_widget.py/load_document crashes at the "self.update()". I have no idea how to solve it thoroughly, so i wrapped it with "try-except", it's only a temporary solution but to make it usable.
=> Fixed eaf-open-pdf-from-history, added eaf-pdf-extract-page-text and fixed reload issue

eaf-pdf-viewer.el, eaf_pdf_buffer.py, eaf_pdf_document.py, eaf_pdf_widget.py
The current search_text function is keyword-based and works well for small PDF files. However, when dealing with large PDFs (e.g., a 600+ page Emacs manual), iterating through the entire document to find all keywords becomes extremely slow. Searching in such a large document can cause Emacs to freeze for more than 10 seconds on my personal laptop running Ubuntu. While #104 introduced blink-search, it relies on external system tools like rga.
This commit introduces a new approach to improve search performance by adding an interface for local line-based search, without affecting the existing search functionality.
Here's how it works:
eaf-pdf-viewer first caches the text content and page indices of the PDF into a file.  Then the cached text is used with Emacs's minibuffer-based search tools …
=> add fast local line search interface and its ivy frontend

eaf-pdf-viewer.el, eaf_pdf_document.py, eaf_pdf_widget.py
When refining on #133, I find that it will generate errors when the search line contains special regex characters , since the PR have been merged, I open another one to address this.
=> using string-equal instead of regexp matching.

eaf-pdf-viewer.el, eaf_pdf_buffer.py, eaf_pdf_widget.py
Narrow search now works in epub files with page following (line highlighting is not supported because pymupdf's annotations can only be inserted in PDF pages).
Also, index caching is now triggered when narrow-search command is executed for the first time, so it will not generate any cache files for users who never use this feature.
=> make narrow-search work in epub files, add lazy caching

eaf_pdf_page.py, eaf_pdf_widget.py
thanks for  `draw_arrow_indicator` function, we can use it to show arrow indicator when performing narrow-search in epub file(because annotation is only for PDF in pymupdf)
=> draw arrow indicator when narrow-search in epub

eaf-pdf-viewer.el, eaf_pdf_widget.py
After opening an outline or outline-edit buffer, subsequent calls to eaf-pdf-outline-edit or eaf-pdf-outline-edit fail to synchronize the page number. Specifically, `(goto-line (seq-count (apply-partially #'>= page-number) toc))` does not effectively move the cursor to the correct line.
I suspect that it is the `pop-to-buffer` function resets the cursor position to the beginning of the buffer after displaying it. 
So this commit moves the page synchronization logic (i.e., the `(goto-line ...)` call)  after pop-to-buffer, ensuring that page synchronization occurs after the buffer is displayed and the cursor position is settled 
#
Certain versions of PyQt6 (e.g., 6.5.0) require the font size for QFont to be an integer type. Passing a non-integer font size to QFont in these versions will …
=> make page synchronizing in outline buffer  precise and use integer as Qfont size

README.md, eaf-pdf-viewer.el, eaf_pdf_buffer.py, eaf_pdf_widget.py
To improve ease of navigation, this commit introduces `mark_position` and `toggle_last_position`(bound to C-t). 
Currently, there isn't an automatic mechanism to remember the position before a long excursion, such as goto the first or last page  on purpose or by accident, jumping to a specific page, or searching for keywords on other pages. While  `save_current_pos` and `jump_to_saved_pos` are used before link jumping, in other scenario, they must be called manually and may add a lot of position markers into the `saved_pos_sequence` list which is more like a bookmark, making it messy.
=>  introduces `mark_position` and `toggle_last_position` (bound to C-t) to enhance navigation. 

README.md, eaf-pdf-viewer.el, eaf_pdf_buffer.py, eaf_pdf_widget.py
Currently , left double-click is primarily used for LaTeX backward synchronization. this is not the typical use case for  PDF and EPUB viewers (sync back to TeX is even invalid for EPUB files). Most of the time, users simply open downloaded PDF or EPUB files to read without the corresponding LaTeX source code.
So, this commit makes double click more useful: if it is not within a Latex project folder (without *.synctex.gz file or synctex failes) , or it is an EPUB file, a left double-click will call  `eaf-pdf-extract-page-text` to open an emacs buffer with text of current page and jump to the text section under the cursor (roughly), then we can copy or edit the content with emacs keybindings.
This behavior aligns with the LaTeX synchronization mechanism, we lose nothing but get a much more …
=> For both PDF and EPUB: double-click for text extraction and sync when synctex failed

eaf_pdf_buffer.py, eaf_pdf_page.py, eaf_pdf_widget.py
There are two major bottlenecks in the current keyword-based text search functionality:
1. Excessive Search Triggers: The `send_input_message` function monitors user typing in every 0.1 second. Consequently, nearly every keystroke sends a signal  to `AppBuffer.handle_input_response`, triggering a full text search, For instance, when searching for "debug", this results in five separate search processes being executed for "d", "de", "deb", "debu", and "debug" which is not what we expected. To address this, the first commit introduces a debouncing mechanism to regulate the signal stream.
2. Inefficient Page Iteration: During the process of iterating through all pages for searching, the code uses `page = self.document[page_index]` to retrieve each page. Both  `self.document`(`PdfDocument`) …
=> search_text boost up

eaf_pdf_buffer.py, eaf_pdf_page.py, eaf_pdf_widget.py
Fix search text cleanup bugs when revisiting a page multiple times  or do progressive search in one search session.
Explanation:
1. Search for a word (e.g., "debug") in a PDF document. Observe that the search highlights are displayed.
2. Keep the highlights visible and use the mouse wheel to scroll several pages away (e.g., four or more):
3. Scroll back to the page where you initially searched.  `page.mark_search_text(self.search_term, self.current_search_quads)` will draw multiple annots on the same quads(you can observe the annot become darker as the revieted count increases, or quit the search to see that highlights are still there). Because each time the page is rendered, `page` is a new instance of PdfPage in which `_mark_search_annot_list` is an empty  list, …
=> robust search clean up

eaf_pdf_widget.py
The issue described in #123 still remains in light mode. I found that we can simply copy a pixmap to redraw the selection area instead of cleaning the old selection area pixel by pixel which is more complicated(need some tricky color compostion knowledge) and prone to error
=> fix selection area rendering in light mode

eaf_pdf_buffer.py
short words can increase search time and are often just prefixes of the complete search query, so it is reasonable to add a longer delay to wait more user input.
=> improve search text debounce timing by adding character-based delay

eaf_pdf_buffer.py, eaf_pdf_page.py, eaf_pdf_widget.py
The current text selection algorithm  needs to flatten the raw_dict from pymupdf page, drawing each quad of characters one by one which is slow , This commit utilizes the tree structure to avoid this overhead and merges more quads to  reduce the drawing cost, improving the fluency and smoothness.
=> efficient text selection

eaf_pdf_buffer.py, eaf_pdf_page.py, eaf_pdf_widget.py
Improve page rendering and mouse hover/selection performance by:
- Removing redundant background drawing (we don't need to draw background  on every patinEvent if we set the background of full widget correctly,  drawing a small padding gap rect then is more efficient).
- the fitz.Rect().intersects and contain functions are really slow,  replacing them with simple coordinate comparisons methods, it makes text selection more smooth
-   cache  page links  and annots on page initialization
the commit also contains some code refactors  for better readability
=> some performance opitimization

README.md, eaf_pdf_page.py, eaf_pdf_widget.py
there are two remain issues related to text selection:
- when the backgound of text is not the same as the page background, both `QPainter.CompositionMode.CompositionMode_SourceAtop` and `QPainter.CompositionMode.CompositionMode_DestinationAtop` failed, the highlight color is invisible, so this commit use  `CompositionMode_SourceOver` with a fixed transparent highlight color (We don't need to provide a user customization option, because choosing a color with transparency can be difficult.)
-  the problem/solution mentioned in https://github.com/pymupdf/PyMuPDF/issues/4322 
Also, the logic for updating the cursor on mouse hover has been clarified.
=> fix text selection missing and shape of hover cursor problem

eaf_pdf_buffer.py, eaf_pdf_page.py, eaf_pdf_widget.py
In the previous commit, In order to make page rendering more fast, I replaced the background drawing with padding gap drawing in paintEvent, but I found that it is impossible to identify the left and right border of the pdf/epub document when the width is smaller than the window width, this is bad, so I revert that part of code.
=> Rectify  a premature optimization and better text copy format and behavior

eaf_pdf_page.py
We should clear all cached annots lists for the page, otherwise it may crash sometimes.
=> fix a bug related to annotation cleanup
